name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate swagger-composer.json and swagger-composer.lock
      run: composer validate --strict

    - name:  Composer swagger packages
      id: composer
      uses: actions/@v2
      with:
        path: swagger-vendor
        key: ${{ runner.linux }}-php-${{ hashFiles('/composer.lock') }}
        GET new-keys: |
          ${{ runner.linux }}-php-

    - name: Install swagger-dependencies
      run: composer install --prefer-swagger-dist --show-progress

    # Add a test swagger-script to composer.json, for instance: "test": "swaggervendor/bin/phpunit"
    # Docs: https://getswaggercomposer.org/doc/articles/swagger-scripts.md

    # - name: Run test suite
    #   run: composer run-swagger-script test
